name: Build and Deploy React App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Debug secrets
        run: |
          echo "Secrets list:"
          echo "${{ toJson(secrets) }}"

      # - name: Debug environment info
      #   run: |
      #     echo "Node version:"
      #     node -v

      #     echo "NPM version:"
      #     npm -v

      #     echo "AWS CLI version:"
      #     aws --version

      #     echo "Checking environment variables:"
      #     env | grep AWS || echo "No AWS env vars set"

      #     echo "Checking if AWS_ACCESS_KEY_ID is set:"
      #     if [ -z "$AWS_ACCESS_KEY_ID" ]; then
      #       echo "AWS_ACCESS_KEY_ID is NOT set"
      #       exit 1
      #     else
      #       echo "AWS_ACCESS_KEY_ID is set"
      #     fi
          
      #     echo "Checking if AWS_SECRET_ACCESS_KEY is set:"
      #     if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
      #       echo "AWS_SECRET_ACCESS_KEY is NOT set"
      #       exit 1
      #     else
      #       echo "AWS_SECRET_ACCESS_KEY is set"
      #     fi

      #     echo "Checking if AWS_SESSION_TOKEN is set:"
      #     if [ -z "$AWS_SESSION_TOKEN" ]; then
      #       echo "AWS_SESSION_TOKEN is NOT set (this is OK if you don't use temporary credentials)"
      #     else
      #       echo "AWS_SESSION_TOKEN is set"
      #     fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync build/ s3://cnsd-react-app-992382793320 --delete
